### ISSUE TITLE
Unable to download spectator data

### ISSUE THREAD

**Issue by dustinlieu** [1lann/lol-replay#2]
I tried to spectate through the LoL Spectator tool, but the game freezes at the loading screen and then pops up a message saying "Unable to download spectator data. The game will now exit." I've attached my spectator file below. It doesn't seem to be working with any game I record.

![screen shot 2016-07-09 at 8 25 19 pm](https://cloud.githubusercontent.com/assets/18184165/16711492/9c3c5bd0-4613-11e6-954d-75bcc75b8e75.png)

[NA1_2237346826.glr.zip](https://github.com/1lann/lol-replay/files/355829/NA1_2237346826.glr.zip)

**Comment by 1lann** [comment]
Seems to be resolved.
